services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - web_migrations
  web_migrations:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code