# Generated by Django 4.1.7 on 2023-02-19 23:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload_data',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='upload date'),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
