# Generated by Django 4.1.7 on 2023-02-20 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_app', '0003_alter_image_image_alter_thumbnail_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='account_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='image_app.accounttier'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
