# Generated by Django 4.1.7 on 2023-02-27 17:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_app', '0010_alter_image_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttier',
            old_name='expiring_link',
            new_name='can_access_original_file',
        ),
        migrations.RenameField(
            model_name='accounttier',
            old_name='originally_uploaded_file',
            new_name='can_generate_expiring_links',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='upload_data',
            new_name='upload_date',
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('title', 'user')},
        ),
    ]
