# Generated by Django 4.1.7 on 2023-02-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0012_image_uuid_field_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='size',
            field=models.IntegerField(verbose_name='thumbnail height'),
        ),
    ]
